[build]
builder = "NIXPACKS"
buildCommand = "apt-get update && apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev libpixman-1-dev && npm install && npm run build"
